# Generated by Django 4.2.6 on 2023-11-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_club_record_sotuv_alter_club_record_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='presidend',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
