# Generated by Django 4.2.6 on 2023-11-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_hmavsum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
