# Generated by Django 4.2.6 on 2023-11-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0006_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='eski',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotuvlari', to='asosiy.club'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='yangi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olganlari', to='asosiy.club'),
        ),
    ]
