# Generated by Django 4.2.6 on 2023-11-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0007_alter_transfer_eski_alter_transfer_yangi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
