# Generated by Django 4.2.6 on 2023-11-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0009_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='mavsum',
            field=models.CharField(default='22-23', max_length=10),
        ),
    ]
